format_version: v1.0
type: UniqueComponent
attributes: {id: rstc}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: WAKEUP_ENABLE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rstc, value: '0'}
- type: ElementPosition
  attributes: {x: '547', y: '98', id: rstc}
