format_version: v1.0
type: UniqueComponent
attributes: {id: supc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: SUPC_VREF_SEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '7'}
- type: ElementPosition
  attributes: {x: '527', y: '180', id: supc}
