format_version: v1.0
type: UniqueComponent
attributes: {id: pm}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: PM_PLCFG_PLSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pm, value: '1'}
  - type: Boolean
    attributes: {id: PM_STDBYCFG_DPGPD0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: PM_STDBYCFG_DPGPD1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: PM_STDBYCFG_LINKPD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: KeyValueSet
    attributes: {id: PM_STDBYCFG_PDCFG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: PM_STDBYCFG_VREGSMOD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
- type: ElementPosition
  attributes: {x: '402', y: '136', id: pm}
