configName: sam_l21_xpro
folderName: sam_l21_xpro
format_version: v1.0
frameworkPath: ..\..\..\..\..
processor: ATSAML21J18B
projectName: usart_sof_interrupt_sam_l21_xpro
settings:
  PackageFilter: csp;csp_apps_pic32cm_le_ls;csp_apps_sam_c20_c21;csp_apps_sam_d5x_e5x;csp_apps_sam_g55;csp_apps_sam_l10_l11;csp_apps_sam_l21;dev_packs;harmony-services;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML21_DFP\3.5.87\saml21b\atdf\ATSAML21J18B.atdf
